# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the datbase
datasources:
#   # <string, required> name of the datasource. Required
 - name: InfluxDB-v2
#   # <string, required> datasource type. Required
   type: influxdb
#   # <string, required> access mode. direct or proxy. Required
   access: proxy
#   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
#   # <string> url
   url: http://influxdb:8086
#   # <string> database password, if used
#   password: 
#   # <string> database user, if used
#   user: 
#   # <string> database name, if used
#   database: edgedb
#   # <bool> enable/disable basic auth
   basicAuth: true
#   # <string> basic auth username
   basicAuthUser: admin
#   # <string> basic auth password
   basicAuthPassword: adminadmin
#   # <bool> enable/disable with credentials headers
#   withCredentials:
#   # <bool> mark as default datasource. Max one per org
   isDefault: false
#   # <map> fields that will be converted to json and stored in json_data
   jsonData:
      defaultBucket: edgedb
      httpMode: POST
      maxSeries: 1000
      organization: siemens
      timeInterval: 10s
      version: Flux
      #token: adF_T8iIgUuWdVQfVg75oWrudqbGuqYS7dkJ3fBeoCnfTi0J0nlmcj_GtZpuuHhZkB1PrNqa3o8Wgu9tyQiI3w==
   readOnly: false
#   # <string> json object of data that will be encrypted.
   secureJsonData:
     token: testtoken
#     tlsClientCert: "..."
#     tlsClientKey: "..."
#     # <openshift\kubernetes token example>
#     httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
#   version: 1
#   # <bool> allow users to edit datasources from the UI.
#   editable: false
